### ISSUE TITLE
Add release build checks/features

### ISSUE THREAD

**Issue by taqtiqa-mark** [zombiezen/redo-rs#16]
Which of the following would be accepted if added to as GH actions or workflows?

- [x] Security audit check of crate dependencies: PR #20 
- [x] Stable + beta + nightly + MSRV:  
  - PR #20: Adds MSRV
- [x] Parallel executions:
    `cargo check`
    `cargo test`
    `cargo fmt`
    `cargo clippy`

**Comment by zombiezen** [comment]
> * [ ]  Security audit check of crate dependencies

I'm assuming this would be a Dependabot configuration? Sure.

> * [ ]  Stable + beta + nightly + MSRV

I don't know what this means.

> * [ ]  Parallel executions:
>   `cargo check`
>   `cargo test`
>   `cargo fmt`
>   `cargo clippy`

`cargo test` already gets run as part of the [Build workflow](https://github.com/zombiezen/redo-rs/blob/main/.github/workflows/build.yml), and IIUC covers everything `cargo check` would. I do have a separate [check target](https://github.com/zombiezen/redo-rs/blob/main/check.do) that I run locally during development. I'm not opposed to adding the others, but I would prefer they get added as redo targets so that they can be run locally.

**Comment by taqtiqa-mark** [comment]
> >         Stable + beta + nightly + MSRV
>
> I don't know what this means.

Build against more than stable channel.  Does introduce a MSRV but that is relevant only for people who need to build locally, or developers.

> ... but I would prefer they get added as redo targets so that they can be run locally.

Ok, this proposal is around GH actions (which I usually run locally), so I'll leave that to another time.

Am I right to infer there is a preference to have CI/CD type activities be independent of the CI service, i.e. as local redo scripts using git hooks?  
If so might be worth adding to a contributing section with some guidance, e.g. are the git hooks in scope?

**Comment by zombiezen** [comment]
> Build against more than stable channel. Does introduce a MSRV but that is relevant only for people who need to build locally, or developers.

I don't see a reason to build with anything other than Rust stable. This isn't intended to be a Rust library crate: it's a binary program.

> Am I right to infer there is a preference to have CI/CD type activities be independent of the CI service, i.e. as local redo scripts using git hooks?

Not necessarily using Git hooks, but yes, as redo targets.

> If so might be worth adding to a contributing section with some guidance, e.g. are the git hooks in scope?

I haven't added any contribution documentation because I'm not regularly onboarding contributors for this project. Mostly this has been published as a proof of concept, and isn't anywhere near stable.

**Comment by taqtiqa-mark** [comment]
Closing as out of scope of GH actions.
